### ISSUE TITLE
함수 filetime1 테스팅 (파일1 시간 받아오기)

### ISSUE THREAD

**Issue by ChoiYuLim** [lamlyg/Assignment2#11]
함수 filetime1  (file1 시간 받아오기) 테스팅

**Comment by ChoiYuLim** [comment]
![image](https://user-images.githubusercontent.com/52950523/82016158-5b1e8900-96bb-11ea-870f-ea9026078a46.png)

![image](https://user-images.githubusercontent.com/52950523/82016188-696ca500-96bb-11ea-9f71-12458bda5c82.png)

정상적으로 동작합니다.

**Comment by lamlyg** [comment]
네, 확인했습니다. 감사합니다.
