### ISSUE TITLE
함수 filetime2 테스팅 (파일2 시간 받아오기)

### ISSUE THREAD

**Issue by ChoiYuLim** [lamlyg/Assignment2#13]
함수 filetime2 (file2 시간 받아오기) 테스팅

**Comment by ChoiYuLim** [comment]
![image](https://user-images.githubusercontent.com/52950523/82016783-b9983700-96bc-11ea-99a3-1921b4964c4f.png)
![image](https://user-images.githubusercontent.com/52950523/82016797-c026ae80-96bc-11ea-940d-a0ee039a4933.png)

정상적으로 작동됩니다.

**Comment by lamlyg** [comment]
네, 확인했습니다 !
