### ISSUE TITLE
함수 sizecmp 테스팅 (파일 사이즈 비교)

### ISSUE THREAD

**Issue by lamlyg** [lamlyg/Assignment2#17]
함수 sizecmp (파일 사이즈 비교 함수) 테스팅

**Comment by lamlyg** [comment]
![image](https://user-images.githubusercontent.com/33417495/82019451-37127600-96c2-11ea-958f-9a4269730866.png)
(ls -al 결과)

![image](https://user-images.githubusercontent.com/33417495/82019469-3ed21a80-96c2-11ea-8842-2232f6d07d7b.png)
(함수에 대한 결과)

정상적으로 동작합니다.

**Comment by ChoiYuLim** [comment]
좋습니다.
