### ISSUE TITLE
함수 datecmp 수정 및 보완

### ISSUE THREAD

**Issue by lamlyg** [lamlyg/Assignment2#28]
함수 datecmp의 기능이 잘못구현되었습니다. 
수정 및 보완하여 다시 구현하겠습니다.

**Comment by lamlyg** [comment]
![image](https://user-images.githubusercontent.com/33417495/82039045-5e2b7080-96df-11ea-8d34-6fc2d593fc4b.png)
( ls -al 을 이용하여, 확인한 text1, text2에 대한 결과 )
==> text1이 더 먼저 만들어진 파일이므로, text2가 최근에 만든 파일입니다

![image](https://user-images.githubusercontent.com/33417495/82039137-84e9a700-96df-11ea-9d25-ced4bf2f2771.png)
(함수 datecmp에 대해, 수정한 결과를 다음과 같이 확인할 수 있습니다.)

**Comment by ChoiYuLim** [comment]
넵
