### ISSUE TITLE
함수 filestat1 테스팅 (파일1 정보 받아오기)

### ISSUE THREAD

**Issue by lamlyg** [lamlyg/Assignment2#5]
함수 filestat1에 대한 구현 후, 테스트 결과 확인하기

**Comment by lamlyg** [comment]
gcc 컴파일을 통해, 확인한 결과입니다.
정상적으로 동작합니다.

![image](https://user-images.githubusercontent.com/33417495/82014031-ac784980-96b6-11ea-9388-27d6de598040.png)

**Comment by ChoiYuLim** [comment]
확인했습니다.
