### ISSUE TITLE
함수 filestat2 테스팅 (파일2 정보 받아오기)

### ISSUE THREAD

**Issue by lamlyg** [lamlyg/Assignment2#8]
함수 filestat2 테스팅 결과 첨부 예정

**Comment by lamlyg** [comment]
![image](https://user-images.githubusercontent.com/33417495/82014830-5f957280-96b8-11ea-930a-0ef462a230f8.png)
( 함수 구현에 대한 gcc 컴파일 결과)

![image](https://user-images.githubusercontent.com/33417495/82014877-75a33300-96b8-11ea-8b2b-f5f453e7876b.png)
( 리눅스 ls -al에 대한 파일 text1, text2에 대한 결과)

=> 정상적으로 구현되었습니다.

**Comment by ChoiYuLim** [comment]
네 확인했습니다.
